### ISSUE TITLE
Verification does not work, if Service is not created

### ISSUE THREAD

**Issue by manne** [rbengtsson/Automoqer#3]
Given the following code
```csharp
void Main()
{
	using(var moqer = new AutoMoqer<EventConsumer>().Build())
	{
		moqer.Param<IDependency>().Setup(d => d.Register());
		moqer.Param<ICrazyEventEmiter>().Raise(e => e.Foo += null, EventArgs.Empty);
	}
}

public class EventConsumer
{
	public EventConsumer(ICrazyEventEmiter eventEmiter, IDependency dependency)
	{
		eventEmiter.Foo += (sender, args) =>
		{
			dependency.Register();
		};
	}	
}

public interface IDependency
{
	void Register();
}

public interface ICrazyEventEmiter
{
	event EventHandler Foo;
}
```
Running this snippet with LINQPad will result in `MockException: The following setups were not matched:
IDependency d => d.Register()`
Reason: the service (instance of `EventConsumer`) is not created.

Changing the code to the following, the expected behavior is met.
```csharp
void Main()
{
	using(var moqer = new AutoMoqer<EventConsumer>().Build())
	{
                var unused = moqer.Service;
		moqer.Param<IDependency>().Setup(d => d.Register());
		moqer.Param<ICrazyEventEmiter>().Raise(e => e.Foo += null, EventArgs.Empty);
	}
}

// ...
```
However SonarQube/SonarLint reports a violation [S1481](https://rules.sonarsource.com/csharp/RSPEC-1481).

An improvement would be to have a method, like `AutoMoqerContainer<TService>.CreateService():void`, which internally creates the instance.

@rbengtsson if you want to have this feature, I will send an PR. As always I am opened for suggestions and/or further improvement.

**Comment by rbengtsson** [comment]
Hi @manne,

Thanks for your quality input. I will gladly accept such PR :)

Kind Regards,
Robert
