### ISSUE TITLE
improved support for aaa pattern

### ISSUE THREAD

**Issue by manne** [rbengtsson/Automoqer#4]
I like the [aaa pattern](http://wiki.c2.com/?ArrangeActAssert). automoqer has still room for improvement regarding to support this pattern. To apply the aaa pattern, a comment has to be written before the end of the using block.

```csharp
void Main()
{
	// Arrange
	using(var moqer = new AutoMoqer<EventConsumer>().Build())
	{
		moqer.Param<IDependency>().Setup(d => d.Register());
		
		// Act
		moqer.Param<ICrazyEventEmiter>().Raise(e => e.Foo += null, EventArgs.Empty);
		
		// Assert
		// is done in moqer.Dispose()
	}
}

public class EventConsumer
{
	public EventConsumer(ICrazyEventEmiter eventEmiter, IDependency dependency)
	{
		eventEmiter.Foo += (sender, args) =>
		{
			dependency.Register();
		};
	}	
}

public interface IDependency
{
	void Register();
}

public interface ICrazyEventEmiter
{
	event EventHandler Foo;
}

```

A possibility is to introduce an explicit method to call the verification, like `AutoMoqerContainer<TService>.VerifyAll():void `.  The disadvantage is that the verification is done twice. This can be mitigated by introducing a class which does not implicitly invoke the verification, e.g `AutoMoqerContainerWithExplicitVerification<TService>`.

@rbengtsson if you want to have this feature, I will send an PR. As always I am opened for suggestions and/or further improvement. Especially in nomenclature 😉

**Comment by rbengtsson** [comment]
Hi @manne,

Thanks for your quality input!
 
I like the idea of having an optional VerifyAll():void to support an explicit aaa-pattern. If method has been invoked, the verification usually done in the Dispose method of AutoMoqerContainer would automatically be skipped.

What do you think about that?

Kind Regards,
Robert

**Comment by manne** [comment]
hi @rbengtsson,
I thought about the proposal. The design would be improved, if the `AutoMoqerContainer.Dispose()` always calls `VerifyAll()`, as it is, so no behavioral change. Additionally  `AutoMoqer` needs a second `Build` method. Which returns an instance of a new class. `AutoMoqerContainerWithExplicitVerification`, this class does not implement `IDisposable`, but has a method `VerifyAll():void`.

What do you think about that?
```csharp
public class AutoMoqer<TService> where TService : class
{
   public AutoMoqer<TService> With<TParam>(object instance) {}
   public AutoMoqer<TService> With(string name, object instance) {}
   public AutoMoqerContainer<TService> Build() {}
   public AutoMoqerContainerWithExplicitVerification<TService> BuildWithExplicitVerification() {}
}

public class AutoMoqerContainerBase<TService>
{
   protected AutoMoqerContainerBase(
            ConstructorInfo primaryConstructor,
            IReadOnlyDictionary<Type, object> exceptionParametersByType,
            IReadOnlyDictionary<string, object> exceptionParametersByName) {}
   public Mock<TParam> Param<TParam>() where TParam : class {}
   public TService Service {get;}
   protected void VerifyAllInstances() {}
}

public class AutoMoqerContainer<TService> : AutoMoqerContainerBase, IDisposable
{
   internal AutoMoqerContainer(
            ConstructorInfo primaryConstructor,
            IReadOnlyDictionary<Type, object> exceptionParametersByType,
            IReadOnlyDictionary<string, object> exceptionParametersByName) {}
   public Mock<TParam> Param<TParam>() where TParam : class {}
   public TService Service {get;}
   protected void VerifyAllInstances() {}
   public void Dispose()
   {
      VerifyAllInstances();
   }
}

public class AutoMoqerContainerWithExplicitVerification<TService> : AutoMoqerContainerBase
{
   internal AutoMoqerContainerWithExplicitVerification(
            ConstructorInfo primaryConstructor,
            IReadOnlyDictionary<Type, object> exceptionParametersByType,
            IReadOnlyDictionary<string, object> exceptionParametersByName) {}
   public Mock<TParam> Param<TParam>() where TParam : class {}
   public TService Service {get;}
   protected void VerifyAllInstances() {}
   public void VerifyAll()
   {
      VerifyAllInstances();
   }
}
```

**Comment by rbengtsson** [comment]
OK sounds great, I'll happily accept such PR. :)

**Comment by rbengtsson** [comment]
Thanks for your PR @manne 👍 Will prepare a new release with your changes shortly
